### ISSUE TITLE
Mails - recognized to be spam - Sender and receiver of notification mail are the same

### ISSUE THREAD

**Issue by samamedick** [oliverklee/ext-seminars#127]
The sender in of the notification mail in function notifyOrganizers() is fetched from the organizer. 
Due the fact both adresses the same (sender/receiver) and sender is an internal mail, most spamfilters will not relay the mail.

Please make the sender of notification mails configurable, in the simplest case make a typoscript switch to use the default system sender email ([MAIL][defaultMailFromAddress] / [MAIL][defaultMailFromName]).

**Comment by oliverklee** [comment]
@samamedick Thanks for the suggestion!

I propose to always use the default from address & name if it is set, and use the first organizer's email as fallback (and issue a deprecation warning so that we can remove this fallback in the future). We should also document this in the changelog and the manual.

What are your thoughts about this?

Would be you be willing to provide a pull request for this?

**Comment by samamedick** [comment]
Implemented and made a pull request

**Comment by oliverklee** [comment]
Fixed by 651c1f35f7ede0667fa842506e35086b16c72938.
