### ISSUE TITLE
[BUG] Accept terms in registration not possible

### ISSUE THREAD

**Issue by leofuehringer** [oliverklee/ext-seminars#188]
Although the hook "accept terms" is set, the errormessage 

> Please accept the terms and conditions in order to register for this event
or
> Bitte akzeptieren Sie die allgemeinen Geschäftsbedingungen, um sich für diese Veranstaltung anzumelden.
is displayed.

I will try to fix this in an PR.

**Comment by leofuehringer** [comment]
- The configuration check ist ok
- jQuery is included in the head
- mkforms ist installed
- one included seminars js: '/typo3conf/ext/seminars/Resources/Public/JavaScript/FrontEnd/FrontEnd.js?1545424422'

In the browser error console are six 404 errors: '/typo3temp/mkforms/javascrip_xxxxxxx.js 404 ()'
In typo3temp is no mkforms folder....
Do you have an idea, how I can fix it?

**Comment by oliverklee** [comment]
Sorry, no, no idea.

**Comment by djangones** [comment]
@leofuehringer I don't know if you've found a solution for this problem yet, but I remember having a similar problem after migrating a complete Typo3 instance to a new server.
It seems to be more of a problem in mkforms, because
after analyzing the sys_log it turned out that after the migration the temp directory /typo3temp/mkforms was not present and therefore a temporary JS file could not be written. After I created the directory manually again, the registration could be completed again. In the newer version of mkforms I think the directory has to be located in /typo3temp/assets/mkforms...

**Comment by dbfischer** [comment]
Thanks a lot for your hint @djangones . This solved the problem for me.
After the update of mkforms the path in typo3temp was wrong.
New path: /typo3temp/**assets**/mkforms

**Comment by oliverklee** [comment]
Fixed in the rewritten registration form. Closing.
