### ISSUE TITLE
Switch \Tx_Oelib_Db calls in the bag builders to the new ConnectionPool

### ISSUE THREAD

**Issue by oliverklee** [oliverklee/ext-seminars#607]
We need to check first whether we need oelib's new `PageRepository` for this.

**Comment by Konafets** [comment]
The only call to `\Tx_Oelib_Db` inside `AbstractBagBuilder` is this one: `\Tx_Oelib_Db::createRecursivePageList($sourcePagePids, $recursionDepth)`, so I would assume that we need the new `PageRepository`.

**Comment by Konafets** [comment]
The new method `findWithinParentPages()` expects an array of uids instead of a comma separated string. It is used inside `AbstractBagBuilder::setSourcePages()`, which also expects comma separated strings. Should I extract the comma separated string inside `setSourcePages()` or do it "right" and pass an array to the method?

What do you think?

**Comment by oliverklee** [comment]
Please let's extract the comma separated string inside `setSourcePages()`, and have a clean-up ticket for the API change to do later.
